var xmlTocData = "";
xmlTocData += '<?xml version=\"1.0\" encoding=\"utf-8\"?>';
xmlTocData += '<CatapultToc Version=\"1\" xmlns:MadCap=\"http://www.madcapsoftware.com/Schemas/MadCap.xsd\" MadCap:ignoredWords=\"\" DescendantCount=\"58\">';
xmlTocData += '    <TocEntry Title=\"Bienvenue au Portail exécutif\" Link=\"/Content/c_welcome.htm\" BreakType=\"chapter\" PageNumberReset=\"reset\" StartSection=\"false\" PageNumber=\"1\" PageLayout=\"/Content/Resources/PageLayouts/Print.flpgl\" ChapterNumberReset=\"reset\" ChapterNumber=\"1\" ChapterNumberFormat=\"decimal\" SectionNumberReset=\"continue\" VolumeNumberReset=\"same\" PageNumberFormat=\"decimal\" ComputedResetPageLayout=\"true\" ComputedFirstTopic=\"true\" DescendantCount=\"57\">';
xmlTocData += '        <TocEntry Title=\"Visiteur de tableaux de bord\" Link=\"/Content/toc_viewer.htm\" BreakType=\"chapter\" StartSection=\"false\" PageNumberReset=\"continue\" PageLayout=\"/Content/Resources/PageLayouts/Print.flpgl\" ComputedResetPageLayout=\"true\" ComputedFirstTopic=\"false\" DescendantCount=\"7\">';
xmlTocData += '            <TocEntry Title=\"Utilisation de la page de connexion\" Link=\"/Content/c_login.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '            <TocEntry Title=\"La barre d\'outils du Portail exécutif\" Link=\"/Content/r_toolbar_2.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '            <TocEntry Title=\"Consultation des tableaux de bord\" Link=\"/Content/c_dashboards_about_2.htm\" BreakType=\"chapter\" StartSection=\"false\" PageNumberReset=\"continue\" PageLayout=\"/Content/Resources/PageLayouts/Print.flpgl\" ComputedResetPageLayout=\"true\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '            <TocEntry Title=\"À propos des résultats\" Link=\"/Content/c_scores_about.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '            <TocEntry Title=\"À propos des résultats ouverts\" Link=\"/Content/c_openends_about.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '            <TocEntry Title=\"À propos des repères\" Link=\"/Content/c_benchmarks_about.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '            <TocEntry Title=\"Partager un tableau de bord\" Link=\"/Content/t_share_2.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '        </TocEntry>';
xmlTocData += '        <TocEntry Title=\"Créateur de tableaux de bord\" Link=\"/Content/toc_creator1.htm\" BreakType=\"chapter\" StartSection=\"false\" PageNumberReset=\"continue\" PageLayout=\"/Content/Resources/PageLayouts/Print.flpgl\" ComputedResetPageLayout=\"true\" ComputedFirstTopic=\"false\" DescendantCount=\"10\">';
xmlTocData += '            <TocEntry Title=\"Utilisation de la page de connexion\" Link=\"/Content/c_login_2.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '            <TocEntry Title=\"La barre d\'outils du Portail exécutif\" Link=\"/Content/r_toolbar.htm\" BreakType=\"chapter\" StartSection=\"false\" PageNumberReset=\"continue\" ChapterNumberReset=\"reset\" ChapterNumber=\"1\" ChapterNumberFormat=\"decimal\" PageLayout=\"/Content/Resources/PageLayouts/Print.flpgl\" SectionNumberReset=\"continue\" VolumeNumberReset=\"same\" ComputedResetPageLayout=\"true\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '            <TocEntry Title=\"Utilisation des tableaux de bord\" Link=\"/Content/c_dashboards_about.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '            <TocEntry Title=\"Partager un tableau de bord\" Link=\"/Content/t_share.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '            <TocEntry Title=\"Ajouter un tableau de bord\" Link=\"/Content/t_dashboard_new.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '            <TocEntry Title=\"Au sujet du Gestionnaire de tableaux de bord\" Link=\"/Content/c_dashboard_manager.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '            <TocEntry Title=\"Utilisation des résultats\" Link=\"/Content/c_scores_ww.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '            <TocEntry Title=\"Utiliser les questions ouvertes\" Link=\"/Content/c_openends_ww.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '            <TocEntry Title=\"Utilisation des repères\" Link=\"/Content/c_benchmarks_ww.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '            <TocEntry Title=\"Sélection d\'une période\" Link=\"/Content/r_date.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '        </TocEntry>';
xmlTocData += '        <TocEntry Title=\"Guide de démarrage rapide\" Link=\"/Content/quickstartmain.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"37\">';
xmlTocData += '            <TocEntry Title=\"Créer une nouvelle mosaïque de résultats\" Link=\"/Content/buildscore1.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"8\">';
xmlTocData += '                <TocEntry Title=\"Créer une nouvelle mosaïque de résultats - Étape 1\" Link=\"/Content/buildscore2.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '                <TocEntry Title=\"Créer une nouvelle mosaïque de résultats - Étape 2\" Link=\"/Content/buildscore3.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '                <TocEntry Title=\"Créer une nouvelle mosaïque de résultats - Étape 3\" Link=\"/Content/buildscore4.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '                <TocEntry Title=\"Créer une nouvelle mosaïque de résultats - Étape 4\" Link=\"/Content/buildscore5.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '                <TocEntry Title=\"Créer une nouvelle mosaïque de résultats - Étape 5\" Link=\"/Content/buildscore6.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '                <TocEntry Title=\"Créer une nouvelle mosaïque de résultats - Étape 6\" Link=\"/Content/buildscore7.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '                <TocEntry Title=\"Créer une nouvelle mosaïque de résultats - Étape 7\" Link=\"/Content/buildscore8.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '                <TocEntry Title=\"Créer une nouvelle mosaïque de résultats - Étape 8\" Link=\"/Content/buildscore9.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '            </TocEntry>';
xmlTocData += '            <TocEntry Title=\"Créer une nouvelle mosaïque de questions ouvertes\" Link=\"/Content/buildopenend1.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"8\">';
xmlTocData += '                <TocEntry Title=\"Créer une nouvelle mosaïque de questions ouvertes - Étape 1\" Link=\"/Content/buildopenend2.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '                <TocEntry Title=\"Créer une nouvelle mosaïque de questions ouvertes - Étape 2\" Link=\"/Content/buildopenend3.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '                <TocEntry Title=\"Créer une nouvelle mosaïque de questions ouvertes - Étape 3\" Link=\"/Content/buildopenend4.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '                <TocEntry Title=\"Créer une nouvelle mosaïque de questions ouvertes - Étape 4\" Link=\"/Content/buildopenend5.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '                <TocEntry Title=\"Créer une nouvelle mosaïque de questions ouvertes - Étape 5\" Link=\"/Content/buildopenend6.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '                <TocEntry Title=\"Créer une nouvelle mosaïque de questions ouvertes - Étape 6\" Link=\"/Content/buildopenend7.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '                <TocEntry Title=\"Créer une nouvelle mosaïque de questions ouvertes - Étape 7\" Link=\"/Content/buildopenend8.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '                <TocEntry Title=\"Créer une nouvelle mosaïque de questions ouvertes - Étape 8\" Link=\"/Content/buildopenend9.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '            </TocEntry>';
xmlTocData += '            <TocEntry Title=\"Créer une nouvelle mosaïque de repères\" Link=\"/Content/buildbenchmark1.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"7\">';
xmlTocData += '                <TocEntry Title=\"Créer une nouvelle mosaïque de repères - Étape 2\" Link=\"/Content/buildbenchmark2.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '                <TocEntry Title=\"Créer une nouvelle mosaïque de repères - Étape 3\" Link=\"/Content/buildbenchmark3.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '                <TocEntry Title=\"Créer une nouvelle mosaïque de repères - Étape 4\" Link=\"/Content/buildbenchmark4.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '                <TocEntry Title=\"Créer une nouvelle mosaïque de repères - Étape 5\" Link=\"/Content/buildbenchmark5.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '                <TocEntry Title=\"Créer une nouvelle mosaïque de repères - Étape 6\" Link=\"/Content/buildbenchmark6.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '                <TocEntry Title=\"Créer une nouvelle mosaïque de repères - Étape 7\" Link=\"/Content/buildbenchmark7.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '                <TocEntry Title=\"Options d’affichage des rapports\" Link=\"/Content/newTileFinal.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '            </TocEntry>';
xmlTocData += '            <TocEntry Title=\"Modifier un rapport existant\" Link=\"/Content/edittile1.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"1\">';
xmlTocData += '                <TocEntry Title=\"Modifier un rapport existant - Étape 1\" Link=\"/Content/edittile2.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '            </TocEntry>';
xmlTocData += '            <TocEntry Title=\"Créer un nouveau tableau de bord \" Link=\"/Content/builddash1.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"4\">';
xmlTocData += '                <TocEntry Title=\"À l\'aide du Épingler bouton \" Link=\"/Content/builddash2.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '                <TocEntry Title=\"À l\'aide du Gestionnaire de tableaux de bord\" Link=\"/Content/builddash4.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '                <TocEntry Title=\"Créer un nouveau tableau de bord - Étape 2 \" Link=\"/Content/builddash3.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '                <TocEntry Title=\"Créer un nouveau tableau de bord - Étape 3 \" Link=\"/Content/builddash5.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '            </TocEntry>';
xmlTocData += '            <TocEntry Title=\"Réglages de la tableaux de bord\" Link=\"/Content/editdash1.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"3\">';
xmlTocData += '                <TocEntry Title=\"Réglages de la tableaux de bord - Étape 1\" Link=\"/Content/editdash2.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '                <TocEntry Title=\"Réglages de la tableaux de bord - Étape 2 \" Link=\"/Content/editdash3.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '                <TocEntry Title=\"Réglages de la tableaux de bord - Étape 3 \" Link=\"/Content/editdash4.htm\" ComputedFirstTopic=\"false\" DescendantCount=\"0\" />';
xmlTocData += '            </TocEntry>';
xmlTocData += '        </TocEntry>';
xmlTocData += '    </TocEntry>';
xmlTocData += '</CatapultToc>';
CMCXmlParser._FilePathToXmlStringMap.Add('Toc', xmlTocData);
