var xmlIndexData = "";
xmlIndexData += '<?xml version=\"1.0\" encoding=\"utf-8\"?>';
xmlIndexData += '<CatapultTargetIndex Count=\"42\">';
xmlIndexData += '    <IndexEntry>';
xmlIndexData += '        <Entries>';
xmlIndexData += '            <IndexEntry Term=\"Benchmarks\">';
xmlIndexData += '                <Entries>';
xmlIndexData += '                    <IndexEntry Term=\"new\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"Working With Benchmarks\" Link=\"/Content/c_benchmarks_ww.htm#kanchor43\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                </Entries>';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Dashboard Creator\" Link=\"/Content/toc_creator1.htm#kanchor23\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"Working With Benchmarks\" Link=\"/Content/c_benchmarks_ww.htm#kanchor41\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Categories\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"About Benckmarks\" Link=\"/Content/c_benchmarks_about.htm#kanchor14\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"Working With Benchmarks\" Link=\"/Content/c_benchmarks_ww.htm#kanchor42\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Compare\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Date Range Selection\" Link=\"/Content/r_date.htm#kanchor45\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Dashboard Manager\">';
xmlIndexData += '                <Entries>';
xmlIndexData += '                    <IndexEntry Term=\"delete dashboard\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"About the Dashboard Manager\" Link=\"/Content/c_dashboard_manager.htm#kanchor38\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                    <IndexEntry Term=\"properties\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"About the Dashboard Manager\" Link=\"/Content/c_dashboard_manager.htm#kanchor38\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                </Entries>';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"About the Dashboard Manager\" Link=\"/Content/c_dashboard_manager.htm#kanchor38\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Dashboard Options\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Viewing Dashboards\" Link=\"/Content/c_dashboards_about_2.htm#kanchor12\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"Viewing Dashboards\" Link=\"/Content/c_dashboards_about.htm#kanchor33\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Dashboards\">';
xmlIndexData += '                <Entries>';
xmlIndexData += '                    <IndexEntry Term=\"Dashboard Manager\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"About the Dashboard Manager\" Link=\"/Content/c_dashboard_manager.htm#kanchor37\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                    <IndexEntry Term=\"delete\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"About the Dashboard Manager\" Link=\"/Content/c_dashboard_manager.htm#kanchor38\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                    <IndexEntry Term=\"new\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"Add A Dashboard\" Link=\"/Content/t_dashboard_new.htm#kanchor36\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                    <IndexEntry Term=\"Viewing\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"Viewing Dashboards\" Link=\"/Content/c_dashboards_about_2.htm#kanchor10\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                    <IndexEntry Term=\"Working with\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"Viewing Dashboards\" Link=\"/Content/c_dashboards_about.htm#kanchor31\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                </Entries>';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Dashboard Creator\" Link=\"/Content/toc_creator1.htm#kanchor20\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Date Range\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Date Range Selection\" Link=\"/Content/r_date.htm#kanchor45\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Feedback\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"About the Login Page\" Link=\"/Content/c_login.htm#kanchor6\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"About the Login Page\" Link=\"/Content/c_login_2.htm#kanchor27\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Help\">';
xmlIndexData += '                <Entries>';
xmlIndexData += '                    <IndexEntry Term=\"about\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"Welcome to Executive Portal\" Link=\"/Content/c_welcome.htm#kanchor1\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                </Entries>';
xmlIndexData += '                <Links />';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Language\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"About the Login Page\" Link=\"/Content/c_login.htm#kanchor5\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"About the Login Page\" Link=\"/Content/c_login_2.htm#kanchor26\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Login\">';
xmlIndexData += '                <Entries>';
xmlIndexData += '                    <IndexEntry Term=\"how to\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"About the Login Page\" Link=\"/Content/c_login.htm#kanchor4\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                            <IndexLink Title=\"About the Login Page\" Link=\"/Content/c_login_2.htm#kanchor25\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                </Entries>';
xmlIndexData += '                <Links />';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Logout\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"About the Executive Portal Toolbar\" Link=\"/Content/r_toolbar_2.htm#kanchor8\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"About the Executive Portal Toolbar\" Link=\"/Content/r_toolbar.htm#kanchor29\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Navigation\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Dashboard Viewer\" Link=\"/Content/toc_viewer.htm#kanchor3\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Open ends\">';
xmlIndexData += '                <Entries>';
xmlIndexData += '                    <IndexEntry Term=\"new\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"Working With Open Ends\" Link=\"/Content/c_openends_ww.htm#kanchor40\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                </Entries>';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Dashboard Creator\" Link=\"/Content/toc_creator1.htm#kanchor22\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"Working With Open Ends\" Link=\"/Content/c_openends_ww.htm#kanchor39\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Password\">';
xmlIndexData += '                <Entries>';
xmlIndexData += '                    <IndexEntry Term=\"change\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"About the Login Page\" Link=\"/Content/c_login.htm#kanchor4\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                            <IndexLink Title=\"About the Login Page\" Link=\"/Content/c_login_2.htm#kanchor25\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                    <IndexEntry Term=\"reset\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"About the Login Page\" Link=\"/Content/c_login.htm#kanchor4\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                            <IndexLink Title=\"About the Login Page\" Link=\"/Content/c_login_2.htm#kanchor25\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                </Entries>';
xmlIndexData += '                <Links />';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Quartiles\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"About Benckmarks\" Link=\"/Content/c_benchmarks_about.htm#kanchor15\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"Working With Benchmarks\" Link=\"/Content/c_benchmarks_ww.htm#kanchor44\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Role-based Usability\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Dashboard Viewer\" Link=\"/Content/toc_viewer.htm#kanchor2\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"Dashboard Creator\" Link=\"/Content/toc_creator1.htm#kanchor17\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Scores\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Dashboard Creator\" Link=\"/Content/toc_creator1.htm#kanchor21\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Set Language\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"About the Login Page\" Link=\"/Content/c_login.htm#kanchor4\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"About the Login Page\" Link=\"/Content/c_login_2.htm#kanchor25\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Share\">';
xmlIndexData += '                <Entries>';
xmlIndexData += '                    <IndexEntry Term=\"cancel\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"Share A Dashboard\" Link=\"/Content/t_share_2.htm#kanchor16\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                            <IndexLink Title=\"Share A Dashboard\" Link=\"/Content/t_share.htm#kanchor35\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                    <IndexEntry Term=\"report\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"Share A Dashboard\" Link=\"/Content/t_share_2.htm#kanchor16\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                            <IndexLink Title=\"Share A Dashboard\" Link=\"/Content/t_share.htm#kanchor35\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                </Entries>';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Viewing Dashboards\" Link=\"/Content/c_dashboards_about_2.htm#kanchor13\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"Viewing Dashboards\" Link=\"/Content/c_dashboards_about.htm#kanchor34\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Show\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Dashboard Creator\" Link=\"/Content/toc_creator1.htm#kanchor19\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Side Navigation\">';
xmlIndexData += '                <Entries>';
xmlIndexData += '                    <IndexEntry Term=\"Menu\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"Dashboard Creator\" Link=\"/Content/toc_creator1.htm#kanchor18\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                </Entries>';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Dashboard Creator\" Link=\"/Content/toc_creator1.htm#kanchor18\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Tiles\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Viewing Dashboards\" Link=\"/Content/c_dashboards_about_2.htm#kanchor11\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"Viewing Dashboards\" Link=\"/Content/c_dashboards_about.htm#kanchor32\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Toolbar\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"About the Executive Portal Toolbar\" Link=\"/Content/r_toolbar_2.htm#kanchor7\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"About the Executive Portal Toolbar\" Link=\"/Content/r_toolbar.htm#kanchor28\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Tools\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Dashboard Creator\" Link=\"/Content/toc_creator1.htm#kanchor24\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Username\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"About the Executive Portal Toolbar\" Link=\"/Content/r_toolbar_2.htm#kanchor9\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"About the Executive Portal Toolbar\" Link=\"/Content/r_toolbar.htm#kanchor30\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '        </Entries>';
xmlIndexData += '        <Links />';
xmlIndexData += '        <SeeAlsoLinks />';
xmlIndexData += '        <IndexControlLinks />';
xmlIndexData += '        <SortAsLinks />';
xmlIndexData += '    </IndexEntry>';
xmlIndexData += '</CatapultTargetIndex>';
CMCXmlParser._FilePathToXmlStringMap.Add('Index', xmlIndexData);
