var xmlStylesheetData = "";
xmlStylesheetData += '<?xml version=\"1.0\" encoding=\"utf-8\"?>';
xmlStylesheetData += '<Stylesheet>';
xmlStylesheetData += '    <Styles>';
xmlStylesheetData += '        <Style Name=\"Header\">';
xmlStylesheetData += '            <Properties>';
xmlStylesheetData += '                <Property Name=\"BorderTop\">solid 1px #D8DFE7</Property>';
xmlStylesheetData += '                <Property Name=\"BorderBottom\">solid 1px #323C47</Property>';
xmlStylesheetData += '                <Property Name=\"BackgroundImage\">url(\'header.png\')</Property>';
xmlStylesheetData += '            </Properties>';
xmlStylesheetData += '        </Style>';
xmlStylesheetData += '        <Style Name=\"Home Button\">';
xmlStylesheetData += '            <Properties>';
xmlStylesheetData += '                <Property Name=\"LabelWithNoneOption\">Página inicial</Property>';
xmlStylesheetData += '            </Properties>';
xmlStylesheetData += '        </Style>';
xmlStylesheetData += '        <Style Name=\"Navigation Element\">';
xmlStylesheetData += '            <Classes>';
xmlStylesheetData += '                <StyleClass Name=\"TOC - Home Page Row\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"LabelWithNoneOption\">Índice analítico</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Index - Home Page Row\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"LabelWithNoneOption\">Índice remissivo</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Glossary - Home Page Row\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"LabelWithNoneOption\">Glossário</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Browse Sequence - Home Page Row\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"LabelWithNoneOption\">Seqüência de leitura</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"About - Home Page Row\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"LabelWithNoneOption\">Sobre</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Index Page\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"SeeReference\">Ver:</Property>';
xmlStylesheetData += '                        <Property Name=\"SeeAlsoReference\">Ver também:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Search Results Page\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"NoResultsFoundString\">Nenhum resultado encontrado.</Property>';
xmlStylesheetData += '                        <Property Name=\"SearchErrorString\">Ocorreu um erro durante a pesquisa. Por favor, tente novamente.</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Index Heading\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"BackgroundImage\">url(\'IndexHeadingBG.png\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Height\">23px</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Glossary Heading\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"BackgroundImage\">url(\'IndexHeadingBG.png\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Height\">23px</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '            </Classes>';
xmlStylesheetData += '        </Style>';
xmlStylesheetData += '        <Style Name=\"Search Bar\">';
xmlStylesheetData += '            <Properties>';
xmlStylesheetData += '                <Property Name=\"BackgroundImage\">url(\'SearchBG.png\')</Property>';
xmlStylesheetData += '            </Properties>';
xmlStylesheetData += '        </Style>';
xmlStylesheetData += '        <Style Name=\"Search Button\">';
xmlStylesheetData += '            <Properties>';
xmlStylesheetData += '                <Property Name=\"LabelWithNoneOption\">Busca</Property>';
xmlStylesheetData += '            </Properties>';
xmlStylesheetData += '        </Style>';
xmlStylesheetData += '        <Style Name=\"Formats\">';
xmlStylesheetData += '            <Properties>';
xmlStylesheetData += '                <Property Name=\"CrossReferenceFormat\">{paratext}</Property>';
xmlStylesheetData += '                <Property Name=\"CrossReferencePrintFormat\">\"{paratext}\" {pageref}</Property>';
xmlStylesheetData += '                <Property Name=\"CrossReferenceBelow\">abaixo</Property>';
xmlStylesheetData += '                <Property Name=\"CrossReferenceAbove\">acima</Property>';
xmlStylesheetData += '                <Property Name=\"CrossReferenceOnPage\">Na página </Property>';
xmlStylesheetData += '                <Property Name=\"CrossReferenceOnPreviousPage\">Na página anterior</Property>';
xmlStylesheetData += '                <Property Name=\"CrossReferenceOnNextPage\">Na página seguinte</Property>';
xmlStylesheetData += '                <Property Name=\"CrossReferenceOnFacingPage\">Na página oposta</Property>';
xmlStylesheetData += '                <Property Name=\"BreadcrumbsYouAreHereText\">Encontram-se aqui: </Property>';
xmlStylesheetData += '                <Property Name=\"KeywordLinkText\">Pesquisar no índice</Property>';
xmlStylesheetData += '                <Property Name=\"KeywordLinkIconAltText\">Keyword Link Icon</Property>';
xmlStylesheetData += '                <Property Name=\"RelatedTopicsText\">Temas relacionados</Property>';
xmlStylesheetData += '                <Property Name=\"RelatedTopicsIconAltText\">Related Topics Link Icon</Property>';
xmlStylesheetData += '                <Property Name=\"ConceptLinkText\">Ver abaixo</Property>';
xmlStylesheetData += '                <Property Name=\"ConceptLinkIconAltText\">Concept Link Icon</Property>';
xmlStylesheetData += '                <Property Name=\"DropDownOpenAltText\">Open</Property>';
xmlStylesheetData += '                <Property Name=\"DropDownClosedAltText\">Closed</Property>';
xmlStylesheetData += '                <Property Name=\"ExpandingOpenAltText\">Open</Property>';
xmlStylesheetData += '                <Property Name=\"ExpandingClosedAltText\">Closed</Property>';
xmlStylesheetData += '                <Property Name=\"GlossaryTermOpenAltText\">Open</Property>';
xmlStylesheetData += '                <Property Name=\"GlossaryTermClosedAltText\">Closed</Property>';
xmlStylesheetData += '                <Property Name=\"TogglerOpenAltText\">Open</Property>';
xmlStylesheetData += '                <Property Name=\"TogglerClosedAltText\">Closed</Property>';
xmlStylesheetData += '            </Properties>';
xmlStylesheetData += '        </Style>';
xmlStylesheetData += '        <Style Name=\"Relationships\">';
xmlStylesheetData += '            <Classes>';
xmlStylesheetData += '                <StyleClass Name=\"concept\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Informações do conceito</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"task\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Tarefas relacionadas</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"reference\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Materiais de referência</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '            </Classes>';
xmlStylesheetData += '        </Style>';
xmlStylesheetData += '        <Style Name=\"TocEntry\">';
xmlStylesheetData += '            <Properties>';
xmlStylesheetData += '                <Property Name=\"TopicIcon\">url(\'Topic.gif\')</Property>';
xmlStylesheetData += '                <Property Name=\"TopicIconAlternateText\">Tópico</Property>';
xmlStylesheetData += '                <Property Name=\"BookIcon\">url(\'Book.gif\')</Property>';
xmlStylesheetData += '                <Property Name=\"BookOpenIcon\">url(\'BookOpen.gif\')</Property>';
xmlStylesheetData += '                <Property Name=\"BookIconAlternateText\">Livro</Property>';
xmlStylesheetData += '                <Property Name=\"MarkAsNewIconAlternateText\">Novo</Property>';
xmlStylesheetData += '            </Properties>';
xmlStylesheetData += '        </Style>';
xmlStylesheetData += '        <Style Name=\"IndexEntry\">';
xmlStylesheetData += '            <Properties>';
xmlStylesheetData += '                <Property Name=\"SeeReference\">Ver:</Property>';
xmlStylesheetData += '                <Property Name=\"SeeAlsoReference\">Ver também:</Property>';
xmlStylesheetData += '            </Properties>';
xmlStylesheetData += '        </Style>';
xmlStylesheetData += '        <Style Name=\"AccordionItem\">';
xmlStylesheetData += '            <Properties>';
xmlStylesheetData += '                <Property Name=\"ItemHeight\">28px</Property>';
xmlStylesheetData += '            </Properties>';
xmlStylesheetData += '            <Classes>';
xmlStylesheetData += '                <StyleClass Name=\"IconTray\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"ItemHeight\">28px</Property>';
xmlStylesheetData += '                        <Property Name=\"BackgroundImage\">url(\'AccordionIconsBackground.jpg\')</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"TOC\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Índice analítico</Property>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'TocIcon.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"BackgroundImage\">url(\'TocAccordionBackground.jpg\')</Property>';
xmlStylesheetData += '                        <Property Name=\"BackgroundImageHover\">url(\'TocAccordionBackground_over.jpg\')</Property>';
xmlStylesheetData += '                        <Property Name=\"ItemHeight\">28px</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Index\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Índice remissivo</Property>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'IndexIcon.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"BackgroundImage\">url(\'IndexAccordionBackground.jpg\')</Property>';
xmlStylesheetData += '                        <Property Name=\"BackgroundImageHover\">url(\'IndexAccordionBackground_over.jpg\')</Property>';
xmlStylesheetData += '                        <Property Name=\"ItemHeight\">28px</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Favorites\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Favoritos</Property>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'FavoritesIcon.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"BackgroundImage\">url(\'FavoritesAccordionBackground.jpg\')</Property>';
xmlStylesheetData += '                        <Property Name=\"BackgroundImageHover\">url(\'FavoritesAccordionBackground_over.jpg\')</Property>';
xmlStylesheetData += '                        <Property Name=\"ItemHeight\">28px</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Glossary\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Glossário</Property>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'GlossaryIcon.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"BackgroundImage\">url(\'GlossaryAccordionBackground.jpg\')</Property>';
xmlStylesheetData += '                        <Property Name=\"BackgroundImageHover\">url(\'GlossaryAccordionBackground_over.jpg\')</Property>';
xmlStylesheetData += '                        <Property Name=\"ItemHeight\">28px</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"BrowseSequence\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Seqüência de leitura</Property>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'BrowsesequencesIcon.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"BackgroundImage\">url(\'BrowsesequencesAccordionBackground.jpg\')</Property>';
xmlStylesheetData += '                        <Property Name=\"BackgroundImageHover\">url(\'BrowsesequencesAccordionBackground_over.jpg\')</Property>';
xmlStylesheetData += '                        <Property Name=\"ItemHeight\">28px</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Search\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Busca</Property>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'SearchIcon.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"BackgroundImage\">url(\'SearchAccordionBackground.jpg\')</Property>';
xmlStylesheetData += '                        <Property Name=\"BackgroundImageHover\">url(\'SearchAccordionBackground_over.jpg\')</Property>';
xmlStylesheetData += '                        <Property Name=\"ItemHeight\">28px</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Community\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Community</Property>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'CommunityIcon.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"BackgroundImage\">url(\'CommunityAccordionBackground.jpg\')</Property>';
xmlStylesheetData += '                        <Property Name=\"BackgroundImageHover\">url(\'CommunityAccordionBackground_over.jpg\')</Property>';
xmlStylesheetData += '                        <Property Name=\"ItemHeight\">28px</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '            </Classes>';
xmlStylesheetData += '        </Style>';
xmlStylesheetData += '        <Style Name=\"ToolbarItem\">';
xmlStylesheetData += '            <Classes>';
xmlStylesheetData += '                <StyleClass Name=\"AccordionTitle\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"ControlType\">AccordionTitle</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"QuickSearch\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'QuickSearch.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"PressedIcon\">url(\'QuickSearch_selected.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"HoverIcon\">url(\'QuickSearch_over.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Pesquisa rápida</Property>';
xmlStylesheetData += '                        <Property Name=\"SearchBoxTooltip\">Caixa de texto para busca rápida</Property>';
xmlStylesheetData += '                        <Property Name=\"ControlType\">QuickSearch</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Logo\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"LogoAlternateText\">Sobre</Property>';
xmlStylesheetData += '                        <Property Name=\"AboutBoxAlternateText\">Sobre</Property>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'LogoIcon.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"ControlType\">Logo</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"ExpandAll\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"ControlType\">ExpandAll</Property>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'Expand.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"HoverIcon\">url(\'Expand_over.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"PressedIcon\">url(\'Expand_selected.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Expandir tudo</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"CollapseAll\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"ControlType\">CollapseAll</Property>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'Collapse.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"HoverIcon\">url(\'Collapse_over.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"PressedIcon\">url(\'Collapse_selected.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Recolher tudo</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"RemoveHighlight\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"ControlType\">RemoveHighlight</Property>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'Highlight.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"HoverIcon\">url(\'Highlight_over.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"PressedIcon\">url(\'Highlight_selected.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Desativar realce de pesquisa</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Print\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"ControlType\">Print</Property>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'Print.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"HoverIcon\">url(\'Print_over.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"PressedIcon\">url(\'Print_selected.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Imprimir tópico</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"ToggleNavigationPane\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'HideNavigation.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"PressedIcon\">url(\'HideNavigation_selected.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"HoverIcon\">url(\'HideNavigation_over.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"CheckedIcon\">url(\'HideNavigation_checked.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Mostrar navegação</Property>';
xmlStylesheetData += '                        <Property Name=\"ShowTooltip\">Ocultar navegação</Property>';
xmlStylesheetData += '                        <Property Name=\"ControlType\">ToggleNavigationPane</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Back\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"ControlType\">Back</Property>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'Back.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"HoverIcon\">url(\'Back_over.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"PressedIcon\">url(\'Back_selected.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Voltar</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Forward\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"ControlType\">Forward</Property>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'Forward.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"HoverIcon\">url(\'Forward_over.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"PressedIcon\">url(\'Forward_selected.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Avançar</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Home\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"ControlType\">Home</Property>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'Home.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"HoverIcon\">url(\'Home_over.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"PressedIcon\">url(\'Home_selected.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Página inicial</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Stop\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"ControlType\">Stop</Property>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'Stop.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"HoverIcon\">url(\'Stop_over.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"PressedIcon\">url(\'Stop_selected.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Parar</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Refresh\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"ControlType\">Refresh</Property>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'Refresh.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"HoverIcon\">url(\'Refresh_over.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"PressedIcon\">url(\'Refresh_selected.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Atualizar</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"SelectTOC\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"ControlType\">SelectTOC</Property>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'SelectToc.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"HoverIcon\">url(\'SelectToc_over.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"PressedIcon\">url(\'SelectToc_selected.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Índice analítico</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"SelectIndex\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"ControlType\">SelectIndex</Property>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'SelectIndex.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"HoverIcon\">url(\'SelectIndex_over.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"PressedIcon\">url(\'SelectIndex_selected.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Índice remissivo</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"SelectSearch\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"ControlType\">SelectSearch</Property>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'SelectSearch.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"HoverIcon\">url(\'SelectSearch_over.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"PressedIcon\">url(\'SelectSearch_selected.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Procurar</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"SelectFavorites\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"ControlType\">SelectFavorites</Property>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'SelectFavorites.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"HoverIcon\">url(\'SelectFavorites_over.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"PressedIcon\">url(\'SelectFavorites_selected.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Favoritos</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"SelectGlossary\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"ControlType\">SelectGlossary</Property>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'SelectGlossary.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"HoverIcon\">url(\'SelectGlossary_over.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"PressedIcon\">url(\'SelectGlossary_selected.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Glossário</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"SelectBrowseSequence\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"ControlType\">SelectBrowseSequence</Property>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'SelectBrowseSequences.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"HoverIcon\">url(\'SelectBrowseSequences_over.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"PressedIcon\">url(\'SelectBrowseSequences_selected.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Seqüência de leitura</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"SelectCommunity\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"ControlType\">SelectCommunity</Property>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'Community.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"HoverIcon\">url(\'Community_over.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"PressedIcon\">url(\'Community_selected.gif\')</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"AddTopicToFavorites\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"ControlType\">AddTopicToFavorites</Property>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'AddTopicToFavorites.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"HoverIcon\">url(\'AddTopicToFavorites_over.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"PressedIcon\">url(\'AddTopicToFavorites_selected.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Acrescentar tópico a favoritos</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"TopicRatings\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Classificação de tópico</Property>';
xmlStylesheetData += '                        <Property Name=\"EmptyIcon\">url(\'Rating0.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"FullIcon\">url(\'RatingGold100.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"RatingSubmittedMessage\">Thank you for submitting your rating!</Property>';
xmlStylesheetData += '                        <Property Name=\"ControlType\">TopicRatings</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"EditUserProfile\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"ControlType\">EditUserProfile</Property>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'EditUserProfile.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"HoverIcon\">url(\'EditUserProfile_over.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"PressedIcon\">url(\'EditUserProfile_selected.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Editar perfil de usuário</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"PreviousTopic\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"ControlType\">PreviousTopic</Property>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'PreviousTopic.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"HoverIcon\">url(\'PreviousTopic_over.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"PressedIcon\">url(\'PreviousTopic_selected.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Tópico anterior</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"NextTopic\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"ControlType\">NextTopic</Property>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'NextTopic.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"HoverIcon\">url(\'NextTopic_over.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"PressedIcon\">url(\'NextTopic_selected.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Tópico seguinte</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"CurrentTopicIndex\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"PaddingLeft\">2px</Property>';
xmlStylesheetData += '                        <Property Name=\"PaddingRight\">2px</Property>';
xmlStylesheetData += '                        <Property Name=\"Label\">Página {n} de {total}</Property>';
xmlStylesheetData += '                        <Property Name=\"ControlType\">CurrentTopicIndex</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Separator\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"SeparatorAlternateText\">Separador</Property>';
xmlStylesheetData += '                        <Property Name=\"ControlType\">Separator</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '            </Classes>';
xmlStylesheetData += '        </Style>';
xmlStylesheetData += '        <Style Name=\"FeedbackUserProfileItem\">';
xmlStylesheetData += '            <Classes>';
xmlStylesheetData += '                <StyleClass Name=\"Username\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Nome do usuário:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"EmailAddress\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Endereço de e-mail:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"FirstName\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Nome:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"MiddleName\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Segundo nome:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"LastName\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Sobrenome:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Address1\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Endereço:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Address2\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Endereço 2:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Address3\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Endereço 3:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Address4\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Endereço 4:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"City\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Cidade:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"State\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Estado:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"PostalCode\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Código de endereçamento postal:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Country\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">País:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Gender\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Gênero:</Property>';
xmlStylesheetData += '                        <Property Name=\"GenderFemaleName\">F</Property>';
xmlStylesheetData += '                        <Property Name=\"GenderMaleName\">M</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Phone1\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Telefone:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Phone2\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Telefone 2:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Phone3\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Telefone 3:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Fax\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Fax:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Birthdate\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Data de nascimento:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Date\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Dia:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Employer\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Empregador:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Occupation\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Profissão:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Department\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Departamento:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Custom1\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">À escolha:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Custom2\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">À escolha 2:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Custom3\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">À escolha 3:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Custom4\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">À escolha 4:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Custom5\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">À escolha 5:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Custom6\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">À escolha 6:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Custom7\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">À escolha 7:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Custom8\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">À escolha 8:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Custom9\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">À escolha 9:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Custom10\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">À escolha 10:</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '            </Classes>';
xmlStylesheetData += '        </Style>';
xmlStylesheetData += '        <Style Name=\"Frame\">';
xmlStylesheetData += '            <Classes>';
xmlStylesheetData += '                <StyleClass Name=\"Toolbar\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"BackgroundImage\">url(\'ToolbarBackground.jpg\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Scrolling\">no</Property>';
xmlStylesheetData += '                        <Property Name=\"Height\">28px</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"TopicToolbar\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Height\">28px</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"NavigationTopDivider\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"BackgroundImage\">url(\'NavigationTopGradient.jpg\')</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"NavigationDragHandle\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"BackgroundImage\">url(\'NavigationBottomGradient.jpg\')</Property>';
xmlStylesheetData += '                        <Property Name=\"BackgroundImagePressed\">url(\'NavigationBottomGradient_selected.jpg\')</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"BodyComments\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Comentários</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '            </Classes>';
xmlStylesheetData += '        </Style>';
xmlStylesheetData += '        <Style Name=\"Control\">';
xmlStylesheetData += '            <Classes>';
xmlStylesheetData += '                <StyleClass Name=\"SearchButton\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Pesquisar</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"SearchBox\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Caixa de texto de pesquisa</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"SearchFiltersLabel\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Filtro</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"SearchUnfilteredLabel\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">não filtrado</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"SearchFavoritesLabel\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Pesquisas favoritas</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"TopicFavoritesLabel\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Tópicos favoritos</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"SearchFavoritesDeleteButton\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'Delete.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"PressedIcon\">url(\'Delete_selected.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"HoverIcon\">url(\'Delete_over.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Excluir favoritos selecionados</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"TopicFavoritesDeleteButton\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'Delete.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"PressedIcon\">url(\'Delete_selected.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"HoverIcon\">url(\'Delete_over.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Excluir favoritos selecionados</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"EmptySearchFavoritesLabel\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">(não há pesquisas salvas)</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">(não há pesquisas salvas)</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"EmptyTopicFavoritesLabel\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">(não há tópicos salvos)</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">(não há tópicos salvos)</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"AddSearchToFavoritesButton\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'AddSearchToFavorites.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"PressedIcon\">url(\'AddSearchToFavorites_selected.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"HoverIcon\">url(\'AddSearchToFavorites_over.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Acrescentar texto a ser procurado</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"IndexSearchBox\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Caixa de texto de pesquisa em índice remissivo</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"SearchResults\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"TableSummary\">This table contains the results of the search that was performed. The first column indicates the search rank and the second column indicates the title of the topic that contains the search result.</Property>';
xmlStylesheetData += '                        <Property Name=\"RankLabel\">Classificação</Property>';
xmlStylesheetData += '                        <Property Name=\"TitleLabel\">Título</Property>';
xmlStylesheetData += '                        <Property Name=\"TopicResultsLabel\">Topic Results</Property>';
xmlStylesheetData += '                        <Property Name=\"CommunityResultsLabel\">Community Results</Property>';
xmlStylesheetData += '                        <Property Name=\"ShowAllCommunityResults\">Show all community results</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"Messages\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Loading\">CARREGANDO</Property>';
xmlStylesheetData += '                        <Property Name=\"LoadingAlternateText\">Carregando</Property>';
xmlStylesheetData += '                        <Property Name=\"NoTopicsFound\">Nenhum tópico encontrado</Property>';
xmlStylesheetData += '                        <Property Name=\"InvalidToken\">Token inválido</Property>';
xmlStylesheetData += '                        <Property Name=\"QuickSearchExternal\">Busca rápida desativada em tópicos externos</Property>';
xmlStylesheetData += '                        <Property Name=\"QuickSearchIE5.5\">Busca rápida desativada no Internet Explorer 5.5</Property>';
xmlStylesheetData += '                        <Property Name=\"RemoveHighlightIE5.5\">Desativar realce não ativo no Internet Explorer 5.5.</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"CommentsAddButton\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'AddComment.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"PressedIcon\">url(\'AddComment_selected.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"HoverIcon\">url(\'AddComment_over.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Adicionar comentário</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"CommentsReplyButton\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'ReplyComment.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"PressedIcon\">url(\'ReplyComment_selected.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"HoverIcon\">url(\'ReplyComment_over.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Resposta ao comentário</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"CommentsRefreshButton\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'RefreshTopicComments.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"PressedIcon\">url(\'RefreshTopicComments_selected.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"HoverIcon\">url(\'RefreshTopicComments_over.gif\')</Property>';
xmlStylesheetData += '                        <Property Name=\"Tooltip\">Atualizar comentários</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"CommentNode\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'Comment.gif\')</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"CommentReplyNode\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Icon\">url(\'CommentReply.gif\')</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"NavigationLinkTop\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Abra Navegação</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"NavigationLinkBottom\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"Label\">Abra Navegação</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '            </Classes>';
xmlStylesheetData += '        </Style>';
xmlStylesheetData += '        <Style Name=\"Dialog\">';
xmlStylesheetData += '            <Classes>';
xmlStylesheetData += '                <StyleClass Name=\"AddComment\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"SubmitButtonLabel\">Submeter:</Property>';
xmlStylesheetData += '                        <Property Name=\"CancelButtonLabel\">Cancelar:</Property>';
xmlStylesheetData += '                        <Property Name=\"TitleLabel\">Adicionar comentário</Property>';
xmlStylesheetData += '                        <Property Name=\"UserNameLabel\">Nome do usuário:</Property>';
xmlStylesheetData += '                        <Property Name=\"SubjectLabel\">Assunto:</Property>';
xmlStylesheetData += '                        <Property Name=\"CommentLabel\">Comentário:</Property>';
xmlStylesheetData += '                        <Property Name=\"CommentLengthExceeded\">O tamanho máximo de comentários foi ultrapassado em {n} caracteres.</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"ReplyComment\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"SubmitButtonLabel\">Enviar</Property>';
xmlStylesheetData += '                        <Property Name=\"CancelButtonLabel\">Cancelar</Property>';
xmlStylesheetData += '                        <Property Name=\"TitleLabel\">Resposta ao comentário:</Property>';
xmlStylesheetData += '                        <Property Name=\"UserNameLabel\">Nome do usuário:</Property>';
xmlStylesheetData += '                        <Property Name=\"SubjectLabel\">Assunto:</Property>';
xmlStylesheetData += '                        <Property Name=\"CommentLabel\">Comentário:</Property>';
xmlStylesheetData += '                        <Property Name=\"OriginalCommentLabel\">Comentário original:</Property>';
xmlStylesheetData += '                        <Property Name=\"CommentLengthExceeded\">O tamanho máximo de comentários foi ultrapassado em {n} caracteres.</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '                <StyleClass Name=\"RegisterUser\">';
xmlStylesheetData += '                    <Properties>';
xmlStylesheetData += '                        <Property Name=\"SubmitButtonLabel\">Enviar</Property>';
xmlStylesheetData += '                        <Property Name=\"CancelButtonLabel\">Cancelar</Property>';
xmlStylesheetData += '                        <Property Name=\"TitleLabel\">Criar perfil de serviço de feedback:</Property>';
xmlStylesheetData += '                        <Property Name=\"EditProfileTitleLabel\">Editar o Feedback Service Profile:</Property>';
xmlStylesheetData += '                        <Property Name=\"UserNameLabel\">Nome do usuário:</Property>';
xmlStylesheetData += '                        <Property Name=\"EmailAddressLabel\">Endereço de e-mail:</Property>';
xmlStylesheetData += '                        <Property Name=\"FirstNameLabel\">Nome:</Property>';
xmlStylesheetData += '                        <Property Name=\"LastNameLabel\">Sobrenome:</Property>';
xmlStylesheetData += '                        <Property Name=\"CountryLabel\">País:</Property>';
xmlStylesheetData += '                        <Property Name=\"PostalCodeLabel\">Código de endereçamento postal:</Property>';
xmlStylesheetData += '                        <Property Name=\"GenderLabel\">Gênero:</Property>';
xmlStylesheetData += '                        <Property Name=\"GenderFemaleName\">F</Property>';
xmlStylesheetData += '                        <Property Name=\"GenderMaleName\">M</Property>';
xmlStylesheetData += '                        <Property Name=\"Registration\">É  necessário inserir um perfil de usuário para fazer comentários neste sistema de ajuda.  Uma mensagem de e-mail será enviada para o endereço que fornecer.  Siga as instruções no e-mail pra concluir a ativação.</Property>';
xmlStylesheetData += '                        <Property Name=\"EditProfileRegistration\">Use este formulário para atualizar o seu perfil. Se atualizar seu endereço eletrônico, será enviado um e-mail para o endereço que você informar.  Siga as instruções contidas no e-mail para completar a ativação.</Property>';
xmlStylesheetData += '                        <Property Name=\"RegistrationSubmit\">Suas informações foram enviadas para o MadCap Software.  Quando as informações tiverem sido processadas, você receberá um e-mail com um link para uma página de verificação. Clique neste link ou copie e cole o link em seu navegador da Web para concluir o registro. </Property>';
xmlStylesheetData += '                        <Property Name=\"RegistrationSubmitNote\">OBSERVAÇÃO: Alguns provedores de serviço utilizam software de filtragem de de e-mail que pode fazer com que seu e-mail seja enviado para a pasta de lixo eletrônico. Se não receber uma notificação por e-mail, verifique se não foi enviado para essa pasta.</Property>';
xmlStylesheetData += '                        <Property Name=\"MissingRequiredField\">Insira um valor para:</Property>';
xmlStylesheetData += '                        <Property Name=\"UpdateSuccess\">Seu perfil foi atualizado com sucesso!</Property>';
xmlStylesheetData += '                        <Property Name=\"EmailNotificationsGroupLabel\">Notificações de e-mail</Property>';
xmlStylesheetData += '                        <Property Name=\"EmailNotificationsHeadingLabel\">Desejo receber um e-mail quando...</Property>';
xmlStylesheetData += '                        <Property Name=\"CommentReplyNotificationLabel\">houver uma resposta a algum de meus comentários</Property>';
xmlStylesheetData += '                        <Property Name=\"CommentSameTopicNotificationLabel\">houver um comentário a respeito de um tema que tenha comentado</Property>';
xmlStylesheetData += '                        <Property Name=\"CommentSameHelpSystemNotificationLabel\">houver um comentário referente a qualquer tema no sistema de ajuda.</Property>';
xmlStylesheetData += '                    </Properties>';
xmlStylesheetData += '                </StyleClass>';
xmlStylesheetData += '            </Classes>';
xmlStylesheetData += '        </Style>';
xmlStylesheetData += '    </Styles>';
xmlStylesheetData += '    <ResourcesInfo>';
xmlStylesheetData += '        <Resource Name=\"QuickSearch.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"QuickSearch_selected.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"QuickSearch_over.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"LogoIcon.gif\" Width=\"111\" Height=\"24\" />';
xmlStylesheetData += '        <Resource Name=\"Expand.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Expand_over.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Expand_selected.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Collapse.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Collapse_over.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Collapse_selected.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Highlight.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Highlight_over.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Highlight_selected.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Print.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Print_over.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Print_selected.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"HideNavigation.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"HideNavigation_selected.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"HideNavigation_over.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"HideNavigation_checked.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Back.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Back_over.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Back_selected.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Forward.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Forward_over.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Forward_selected.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Home.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Home_over.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Home_selected.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Stop.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Stop_over.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Stop_selected.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Refresh.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Refresh_over.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Refresh_selected.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"SelectToc.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"SelectToc_over.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"SelectToc_selected.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"SelectIndex.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"SelectIndex_over.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"SelectIndex_selected.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"SelectSearch.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"SelectSearch_over.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"SelectSearch_selected.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"SelectFavorites.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"SelectFavorites_over.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"SelectFavorites_selected.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"SelectGlossary.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"SelectGlossary_over.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"SelectGlossary_selected.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"SelectBrowseSequences.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"SelectBrowseSequences_over.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"SelectBrowseSequences_selected.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Community.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Community_over.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Community_selected.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"AddTopicToFavorites.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"AddTopicToFavorites_over.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"AddTopicToFavorites_selected.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Rating0.gif\" Width=\"16\" Height=\"16\" />';
xmlStylesheetData += '        <Resource Name=\"RatingGold100.gif\" Width=\"16\" Height=\"16\" />';
xmlStylesheetData += '        <Resource Name=\"EditUserProfile.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"EditUserProfile_over.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"EditUserProfile_selected.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"PreviousTopic.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"PreviousTopic_over.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"PreviousTopic_selected.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"NextTopic.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"NextTopic_over.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"NextTopic_selected.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"TocIcon.gif\" Width=\"16\" Height=\"16\" />';
xmlStylesheetData += '        <Resource Name=\"TocAccordionBackground.jpg\" Width=\"2\" Height=\"28\" />';
xmlStylesheetData += '        <Resource Name=\"TocAccordionBackground_over.jpg\" Width=\"2\" Height=\"28\" />';
xmlStylesheetData += '        <Resource Name=\"IndexIcon.gif\" Width=\"16\" Height=\"16\" />';
xmlStylesheetData += '        <Resource Name=\"IndexAccordionBackground.jpg\" Width=\"2\" Height=\"28\" />';
xmlStylesheetData += '        <Resource Name=\"IndexAccordionBackground_over.jpg\" Width=\"2\" Height=\"28\" />';
xmlStylesheetData += '        <Resource Name=\"SearchIcon.gif\" Width=\"16\" Height=\"16\" />';
xmlStylesheetData += '        <Resource Name=\"SearchAccordionBackground.jpg\" Width=\"2\" Height=\"28\" />';
xmlStylesheetData += '        <Resource Name=\"SearchAccordionBackground_over.jpg\" Width=\"2\" Height=\"28\" />';
xmlStylesheetData += '        <Resource Name=\"FavoritesIcon.gif\" Width=\"16\" Height=\"16\" />';
xmlStylesheetData += '        <Resource Name=\"FavoritesAccordionBackground.jpg\" Width=\"2\" Height=\"28\" />';
xmlStylesheetData += '        <Resource Name=\"FavoritesAccordionBackground_over.jpg\" Width=\"2\" Height=\"28\" />';
xmlStylesheetData += '        <Resource Name=\"BrowsesequencesIcon.gif\" Width=\"16\" Height=\"16\" />';
xmlStylesheetData += '        <Resource Name=\"BrowsesequencesAccordionBackground.jpg\" Width=\"2\" Height=\"28\" />';
xmlStylesheetData += '        <Resource Name=\"BrowsesequencesAccordionBackground_over.jpg\" Width=\"2\" Height=\"28\" />';
xmlStylesheetData += '        <Resource Name=\"GlossaryIcon.gif\" Width=\"16\" Height=\"16\" />';
xmlStylesheetData += '        <Resource Name=\"GlossaryAccordionBackground.jpg\" Width=\"2\" Height=\"28\" />';
xmlStylesheetData += '        <Resource Name=\"GlossaryAccordionBackground_over.jpg\" Width=\"2\" Height=\"28\" />';
xmlStylesheetData += '        <Resource Name=\"CommunityIcon.gif\" Width=\"16\" Height=\"16\" />';
xmlStylesheetData += '        <Resource Name=\"CommunityAccordionBackground.jpg\" Width=\"2\" Height=\"28\" />';
xmlStylesheetData += '        <Resource Name=\"CommunityAccordionBackground_over.jpg\" Width=\"2\" Height=\"28\" />';
xmlStylesheetData += '        <Resource Name=\"AccordionIconsBackground.jpg\" Width=\"2\" Height=\"28\" />';
xmlStylesheetData += '        <Resource Name=\"header.png\" Width=\"1\" Height=\"42\" />';
xmlStylesheetData += '        <Resource Name=\"IndexHeadingBG.png\" Width=\"1\" Height=\"23\" />';
xmlStylesheetData += '        <Resource Name=\"SearchBG.png\" Width=\"1\" Height=\"43\" />';
xmlStylesheetData += '        <Resource Name=\"Topic.gif\" Width=\"16\" Height=\"16\" />';
xmlStylesheetData += '        <Resource Name=\"Book.gif\" Width=\"16\" Height=\"16\" />';
xmlStylesheetData += '        <Resource Name=\"BookOpen.gif\" Width=\"16\" Height=\"16\" />';
xmlStylesheetData += '        <Resource Name=\"ToolbarBackground.jpg\" Width=\"2\" Height=\"28\" />';
xmlStylesheetData += '        <Resource Name=\"NavigationTopGradient.jpg\" Width=\"2\" Height=\"8\" />';
xmlStylesheetData += '        <Resource Name=\"NavigationBottomGradient.jpg\" Width=\"2\" Height=\"7\" />';
xmlStylesheetData += '        <Resource Name=\"NavigationBottomGradient_selected.jpg\" Width=\"2\" Height=\"7\" />';
xmlStylesheetData += '        <Resource Name=\"Delete.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Delete_selected.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Delete_over.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"AddSearchToFavorites.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"AddSearchToFavorites_selected.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"AddSearchToFavorites_over.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"AddComment.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"AddComment_selected.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"AddComment_over.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"ReplyComment.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"ReplyComment_selected.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"ReplyComment_over.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"RefreshTopicComments.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"RefreshTopicComments_selected.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"RefreshTopicComments_over.gif\" Width=\"23\" Height=\"22\" />';
xmlStylesheetData += '        <Resource Name=\"Comment.gif\" Width=\"16\" Height=\"16\" />';
xmlStylesheetData += '        <Resource Name=\"CommentReply.gif\" Width=\"16\" Height=\"16\" />';
xmlStylesheetData += '    </ResourcesInfo>';
xmlStylesheetData += '</Stylesheet>';
CMCXmlParser._FilePathToXmlStringMap.Add('Stylesheet', xmlStylesheetData);
