var xmlIndexData = "";
xmlIndexData += '<?xml version=\"1.0\" encoding=\"utf-8\"?>';
xmlIndexData += '<CatapultTargetIndex Count=\"41\">';
xmlIndexData += '    <IndexEntry>';
xmlIndexData += '        <Entries>';
xmlIndexData += '            <IndexEntry Term=\"Afficher\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Créateur de tableaux de bord\" Link=\"/Content/toc_creator1.htm#kanchor19\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Aide\">';
xmlIndexData += '                <Entries>';
xmlIndexData += '                    <IndexEntry Term=\"au sujet de\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"Bienvenue au Portail exécutif\" Link=\"/Content/c_welcome.htm#kanchor1\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                </Entries>';
xmlIndexData += '                <Links />';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Barre d\'outils\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"La barre d\'outils du Portail exécutif\" Link=\"/Content/r_toolbar_2.htm#kanchor7\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"La barre d\'outils du Portail exécutif\" Link=\"/Content/r_toolbar.htm#kanchor28\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Catégorie\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"À propos des repères\" Link=\"/Content/c_benchmarks_about.htm#kanchor14\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"Utilisation des repères\" Link=\"/Content/c_benchmarks_ww.htm#kanchor42\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Commentaires\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Utilisation de la page de connexion\" Link=\"/Content/c_login.htm#kanchor6\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"Utilisation de la page de connexion\" Link=\"/Content/c_login_2.htm#kanchor27\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Comparer\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Sélection d\'une période\" Link=\"/Content/r_date.htm#kanchor45\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"D\'une période\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Sélection d\'une période\" Link=\"/Content/r_date.htm#kanchor45\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"définir la langue\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Utilisation de la page de connexion\" Link=\"/Content/c_login.htm#kanchor4\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"Utilisation de la page de connexion\" Link=\"/Content/c_login_2.htm#kanchor25\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Fermer la session\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"La barre d\'outils du Portail exécutif\" Link=\"/Content/r_toolbar_2.htm#kanchor8\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"La barre d\'outils du Portail exécutif\" Link=\"/Content/r_toolbar.htm#kanchor29\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Gestionnaire de tableaux de bord\">';
xmlIndexData += '                <Entries>';
xmlIndexData += '                    <IndexEntry Term=\"propriétés\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"Au sujet du Gestionnaire de tableaux de bord\" Link=\"/Content/c_dashboard_manager.htm#kanchor38\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                    <IndexEntry Term=\"Supprimer le(s) tableau(x) de bord\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"Au sujet du Gestionnaire de tableaux de bord\" Link=\"/Content/c_dashboard_manager.htm#kanchor38\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                </Entries>';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Au sujet du Gestionnaire de tableaux de bord\" Link=\"/Content/c_dashboard_manager.htm#kanchor38\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Langues\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Utilisation de la page de connexion\" Link=\"/Content/c_login.htm#kanchor5\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"Utilisation de la page de connexion\" Link=\"/Content/c_login_2.htm#kanchor26\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Mosaïques\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Consultation de tableaux de bord\" Link=\"/Content/c_dashboards_about_2.htm#kanchor11\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"Consultation des tableaux de bord\" Link=\"/Content/c_dashboards_about.htm#kanchor32\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Mot de passe\">';
xmlIndexData += '                <Entries>';
xmlIndexData += '                    <IndexEntry Term=\"modifier\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"Utilisation de la page de connexion\" Link=\"/Content/c_login.htm#kanchor4\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                            <IndexLink Title=\"Utilisation de la page de connexion\" Link=\"/Content/c_login_2.htm#kanchor25\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                    <IndexEntry Term=\"réinitialiser\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"Utilisation de la page de connexion\" Link=\"/Content/c_login.htm#kanchor4\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                            <IndexLink Title=\"Utilisation de la page de connexion\" Link=\"/Content/c_login_2.htm#kanchor25\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                </Entries>';
xmlIndexData += '                <Links />';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Navigation latérale\">';
xmlIndexData += '                <Entries>';
xmlIndexData += '                    <IndexEntry Term=\"Menu\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"Créateur de tableaux de bord\" Link=\"/Content/toc_creator1.htm#kanchor18\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                </Entries>';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Créateur de tableaux de bord\" Link=\"/Content/toc_creator1.htm#kanchor18\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Nom d’utilisateur\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"La barre d\'outils du Portail exécutif\" Link=\"/Content/r_toolbar_2.htm#kanchor9\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"La barre d\'outils du Portail exécutif\" Link=\"/Content/r_toolbar.htm#kanchor30\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Options de tableau de bord\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Consultation de tableaux de bord\" Link=\"/Content/c_dashboards_about_2.htm#kanchor12\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"Consultation des tableaux de bord\" Link=\"/Content/c_dashboards_about.htm#kanchor33\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Outils\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Créateur de tableaux de bord\" Link=\"/Content/toc_creator1.htm#kanchor24\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Ouvrir une session\">';
xmlIndexData += '                <Entries>';
xmlIndexData += '                    <IndexEntry Term=\"comment\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"Utilisation de la page de connexion\" Link=\"/Content/c_login.htm#kanchor4\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                            <IndexLink Title=\"Utilisation de la page de connexion\" Link=\"/Content/c_login_2.htm#kanchor25\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                </Entries>';
xmlIndexData += '                <Links />';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Partager\">';
xmlIndexData += '                <Entries>';
xmlIndexData += '                    <IndexEntry Term=\"annuler\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"Partager un tableau de bord\" Link=\"/Content/t_share_2.htm#kanchor16\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                            <IndexLink Title=\"Partager un tableau de bord\" Link=\"/Content/t_share.htm#kanchor35\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                    <IndexEntry Term=\"rapport\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"Partager un tableau de bord\" Link=\"/Content/t_share_2.htm#kanchor16\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                            <IndexLink Title=\"Partager un tableau de bord\" Link=\"/Content/t_share.htm#kanchor35\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                </Entries>';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Consultation de tableaux de bord\" Link=\"/Content/c_dashboards_about_2.htm#kanchor13\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"Consultation des tableaux de bord\" Link=\"/Content/c_dashboards_about.htm#kanchor34\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Quartiles\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"À propos des repères\" Link=\"/Content/c_benchmarks_about.htm#kanchor15\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"Utilisation des repères\" Link=\"/Content/c_benchmarks_ww.htm#kanchor44\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Questions ouvertes\">';
xmlIndexData += '                <Entries>';
xmlIndexData += '                    <IndexEntry Term=\"nouvelle\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"Utiliser les questions ouvertes\" Link=\"/Content/c_openends_ww.htm#kanchor40\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                </Entries>';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Créateur de tableaux de bord\" Link=\"/Content/toc_creator1.htm#kanchor22\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"Utiliser les questions ouvertes\" Link=\"/Content/c_openends_ww.htm#kanchor39\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Repères\">';
xmlIndexData += '                <Entries>';
xmlIndexData += '                    <IndexEntry Term=\"nouvelle\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"Utilisation des repères\" Link=\"/Content/c_benchmarks_ww.htm#kanchor43\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                </Entries>';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Créateur de tableaux de bord\" Link=\"/Content/toc_creator1.htm#kanchor23\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"Utilisation des repères\" Link=\"/Content/c_benchmarks_ww.htm#kanchor41\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Résultats\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Créateur de tableaux de bord\" Link=\"/Content/toc_creator1.htm#kanchor21\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Tableaux de bord\">';
xmlIndexData += '                <Entries>';
xmlIndexData += '                    <IndexEntry Term=\"Consultation\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"Consultation de tableaux de bord\" Link=\"/Content/c_dashboards_about_2.htm#kanchor10\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                    <IndexEntry Term=\"Gestionnaire de tableaux de bord\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"Au sujet du Gestionnaire de tableaux de bord\" Link=\"/Content/c_dashboard_manager.htm#kanchor37\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                    <IndexEntry Term=\"nouvelle\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"Ajouter un tableau de bord\" Link=\"/Content/t_dashboard_new.htm#kanchor36\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                    <IndexEntry Term=\"Supprimer\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"Au sujet du Gestionnaire de tableaux de bord\" Link=\"/Content/c_dashboard_manager.htm#kanchor38\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                    <IndexEntry Term=\"Utilisation des\">';
xmlIndexData += '                        <Entries />';
xmlIndexData += '                        <Links>';
xmlIndexData += '                            <IndexLink Title=\"Consultation des tableaux de bord\" Link=\"/Content/c_dashboards_about.htm#kanchor31\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                        </Links>';
xmlIndexData += '                        <SeeAlsoLinks />';
xmlIndexData += '                        <IndexControlLinks />';
xmlIndexData += '                        <SortAsLinks />';
xmlIndexData += '                    </IndexEntry>';
xmlIndexData += '                </Entries>';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Créateur de tableaux de bord\" Link=\"/Content/toc_creator1.htm#kanchor20\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '            <IndexEntry Term=\"Utilisation basée sur les rôles\">';
xmlIndexData += '                <Entries />';
xmlIndexData += '                <Links>';
xmlIndexData += '                    <IndexLink Title=\"Visiteur de tableaux de bord\" Link=\"/Content/toc_viewer.htm#kanchor2\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"Visiteur de tableaux de bord\" Link=\"/Content/toc_viewer.htm#kanchor3\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                    <IndexLink Title=\"Créateur de tableaux de bord\" Link=\"/Content/toc_creator1.htm#kanchor17\" UsedConditions=\"\" LocalConditions=\"\" />';
xmlIndexData += '                </Links>';
xmlIndexData += '                <SeeAlsoLinks />';
xmlIndexData += '                <IndexControlLinks />';
xmlIndexData += '                <SortAsLinks />';
xmlIndexData += '            </IndexEntry>';
xmlIndexData += '        </Entries>';
xmlIndexData += '        <Links />';
xmlIndexData += '        <SeeAlsoLinks />';
xmlIndexData += '        <IndexControlLinks />';
xmlIndexData += '        <SortAsLinks />';
xmlIndexData += '    </IndexEntry>';
xmlIndexData += '</CatapultTargetIndex>';
CMCXmlParser._FilePathToXmlStringMap.Add('Index', xmlIndexData);
